### ISSUE TITLE
grabinput_variant3.py

### ISSUE THREAD

**Issue by realbuz** [Forceu/barcodebuddy#117]
ok so I'm trying to use the grabinput_variant3.py.  I edited the python file to add my server url, my api key and changed the scanner_str to match my device (/dev/input/event0 in my case) 

when I launch the script nothing happens, nothing visible when I can nor anything on the barcode buddy side.

am I missing something ? 

thanks

**Comment by realbuz** [comment]
ok so I was originally launching it with python (as root).  now I've tried to run it with python3.
I had to install python3-evdev and python3-pyudev

I'm getting a different result this way: 

grabInput_variant3.py:84: DeprecationWarning: Will be removed in 1.0. Access properties with Device.properties.
  for name in (i['NAME'] for i in device.ancestors if 'NAME' in i):

**Comment by realbuz** [comment]
original tests were done against variant3.  

somehow I think I mixed up the one I need to use with variant2.

variant 2 seems to have other issues, first one 
```
`  File "grabInput_variant2.py", line 67
    print 'Please begin scanning...'
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Please begin scanning...')?
```
I added the ( ) to the code.

now I get 

`  File "grabInput_variant2.py", line 72
    if eventdata.keystate == 1:
                              ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by realbuz** [comment]
ok so I replaced all the tabs in this part of the code with space.  I also had to add ( ) to the print `Sending: part.

now I get further but am still stuck 

`Please begin scanning...
Sending:
Traceback (most recent call last):
  File "grabInput_variant2.py", line 75, in <module>
    print ('Sending: ') + barcode
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
`

**Comment by realbuz** [comment]
ok, fixed he print to put the + barcode inside the  () 
print ('Sending: ' + barcode)

now if I scan a code, the code display will show up.

however it's not making it to barcode buddy.

**Comment by realbuz** [comment]
the last used entry for the api key is also not "never" used

**Comment by realbuz** [comment]
got it working, had to change the url to remove barcodebuddy.  I will put in a pull request to change the code to reflect the necessary changes I had to make

**Comment by realbuz** [comment]
I see that there is already a pull request to fix what I have experienced pending.
